name: unit-tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies into venv
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          python3 -m pip install -r dev-requirements.txt --upgrade pip
      - name: Run pytest
        run: |
          source .venv/bin/activate
          pytest